name: BookList CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file
        run: |
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=yourdb" >> .env
          echo "DB_USER=youruser" >> .env
          echo "DB_PASSWORD=yourpassword" >> .env

      - name: Start services
        run: |
          cd BookList
          docker-compose up -d --build

      - name: Wait for health checks
        run: |
          cd BookList
          docker-compose ps
          for i in {1..10}; do
            if docker-compose ps | grep "healthy"; then
              echo "All services healthy."
              exit 0
            fi
            echo "Waiting for services to be healthy..."
            sleep 10
          done
          echo "Services did not become healthy in time."
          docker-compose logs
          exit 1

      - name: Curl BookService
        run: curl --fail http://localhost:9090/swagger/index.html

      - name: Shut down
        run: |
          cd BookList
          docker-compose down -v
