name: BookList CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Increased timeout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Use Docker Compose V2 which is pre-installed on GitHub runners
      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker compose version
          
      - name: Create .env file
        run: |
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=yourdb" >> .env
          echo "DB_USER=youruser" >> .env
          echo "DB_PASSWORD=yourpassword" >> .env
          
      - name: Start services
        run: |
          # Assuming docker-compose.yml is in the root directory
          cd BookList
          docker compose up -d --build
          
      - name: Wait for services to start
        run: |
          echo "Waiting for services to start..."
          sleep 30  # Give more time for services to start
          docker compose ps
          docker compose logs
          
      - name: Check if services are running
        run: |
          if ! docker compose ps --services --filter "status=running" | grep -q "bookservice"; then
            echo "BookService is not running"
            docker compose logs bookservice
            exit 1
          fi
          if ! docker compose ps --services --filter "status=running" | grep -q "authbackend"; then
            echo "AuthBackend is not running"
            docker compose logs authbackend
            exit 1
          fi
          
      - name: Curl BookService
        run: |
          # Add retries for the curl command
          for i in {1..5}; do
            if curl --fail --max-time 10 http://localhost:9090/swagger/index.html; then
              echo "Successfully connected to BookService"
              exit 0
            fi
            echo "Attempt $i failed, retrying in 5 seconds..."
            sleep 5
          done
          echo "Could not connect to BookService"
          exit 1
          
      - name: Shut down
        if: always()
        run: docker compose down -v