name: BookList CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Increased timeout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Docker Compose V2 is pre-installed on GitHub runners
      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker compose version
          
      - name: Create .env file
        run: |
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=yourdb" >> .env
          echo "DB_USER=youruser" >> .env
          echo "DB_PASSWORD=yourpassword" >> .env
          
      - name: Start services
        run: |
          cd BookList
          docker compose up -d --build
          
      # Give services some time to start up and initialize
      - name: Wait for services to initialize
        run: |
          echo "Waiting for services to initialize..."
          sleep 45  # Increased wait time
          cd BookList
          docker compose ps
          docker compose logs
          
      # Check service status
      - name: Check if services are running
        run: |
          cd BookList
          if ! docker compose ps --services --filter "status=running" | grep -q "bookservice"; then
            echo "BookService is not running"
            docker compose logs bookservice
            exit 1
          fi
          echo "BookService is running"
          
          if ! docker compose ps --services --filter "status=running" | grep -q "authbackend"; then
            echo "AuthBackend is not running"
            docker compose logs authbackend
            exit 1
          fi
          echo "AuthBackend is running"
          
      # Try to access the Swagger UI with retries
      - name: Test BookService API
        run: |
          cd BookList
          # Add retries for the curl command
          for i in {1..6}; do
            echo "Attempt $i to connect to BookService..."
            if curl --fail --max-time 10 http://localhost:9090/swagger/index.html; then
              echo "Successfully connected to BookService"
              exit 0
            fi
            echo "Attempt $i failed, retrying in 10 seconds..."
            sleep 10
          done
          echo "Could not connect to BookService after multiple attempts"
          docker compose logs bookservice
          exit 1
          
      # Always shut down services, even if previous steps failed
      - name: Shut down
        if: always()
        run: |
          cd BookList
          docker compose down -v